theme: jekyll-theme-minimal
title: David Carvalho - Desenvolvedor Fullstack
description: Desenvolvedor com experiência em desenvolvimento de aplicativos para dispositivos Android utilizando Java e Kotlin, em desenvolvimento de sites, SaaS e backend com PHP/CakePHP. Atualmente trabalho na manutenção de softwares como serviços, escritos com PHP, e no desenvolvimento de novas soluções em backend com Go e aplicativos móveis com Flutter.
